#!/bin/bash

INSTALL_DIR="/usr/local/bin"
SERVICE_FILE="/lib/systemd/system/gptd.service"
CONFIGURATION_DIR="/etc/gpt.d"


# Create the installation directories
mkdir -p $INSTALL_DIR
mkdir -p $CONFIGURATION_DIR

# Copy the Python files to the installation directory

cp -r usr/local/lib/gpt.d/gptd-uds.py $INSTALL_DIR
chown $SUDO_USER:$SUDO_USER $INSTALL_DIR/gptd-uds.py

# Install the Python requirements
pip install -r $INSTALL_DIR/requirements.txt


# Create the configuration file
cat << EOF >  $CONFIGURATION_DIR/.env
# CONF
# Security
OPENAI_API_KEY=<api key here>

# Flavour
AI_TEXT_COLOUR='\033[34m\033[1m'
AI_NAME_COLOUR='\033[34m\033[1m\033[47m'
TEXT_RESET='\033[0m'
EOF

# Create the service file
cat << EOF > $SERVICE_FILE
[Unit]
Description=gptd

[Service]
ExecStart=/gptd-uds.py
User=$SUDO_USER
Group=$(id -gn $SUDO_USER)
EnvironmentFile=/etc/gpt.d/.env
Restart=no

[Install]
WantedBy=multi-user.target
EOF

# Reload the systemd daemon to recognize the new service
systemctl daemon-reload


