#!/bin/bash

INSTALL_DIR="/usr/local/lib/gpt.d"
SERVICE_FILE="/lib/systemd/system/gptd.service"
CONFIGURATION_DIR="/etc/gpt.d"


# Create the installation directories
mkdir -p $INSTALL_DIR
mkdir -p $CONFIGURATION_DIR

# Copy the Python files to the installation directory
cp -r usr/local/lib/gpt.d/* $INSTALL_DIR

# Install the Python requirements
pip install -r $INSTALL_DIR/requirements.txt

# Create the configuration file
cat << EOF >  $CONFIGURATION_DIR/.env
# CONF
# Security
OPENAI_API_KEY=<api key here>

# Flavour
AI_TEXT_COLOUR='\033[34m\033[1m' # default cyan no background
AI_NAME_COLOUR='\033[34m\033[1m\033[47m' # cyan with white background
TEXT_RESET='\033[0m' # reset
EOF

# Copy the .env to the simpleaichat directory
# cp $CONFIGURATION_DIR/.env
# Create the gptd.service file
cat << EOF > $SERVICE_FILE
[Unit]
Description=gptd

[Service]
ExecStart=/usr/local/lib/gpt.d/gptd-uds.py
User=$SUDO_USER
Group=$(id -gn $SUDO_USER)
EnvironmentFile=/etc/gpt.d/.env
Restart=no

[Install]
WantedBy=multi-user.target
EOF

# Reload the systemd daemon to recognize the new service
systemctl daemon-reload
