#!/bin/bash

INSTALL_DIR="/usr/local/lib/gpt.d"
SERVICE_FILE="/lib/systemd/system/gptd.service"
CONFIGURATION_DIR="/etc/gpt.d/"


# Create the installation directories
mkdir -p $INSTALL_DIR
mkdir -p $CONFIGURATION_DIR

# Copy the Python files to the installation directory
cp -r usr/local/lib/gpt.d/* $INSTALL_DIR

# Install the Python requirements
pip install -r $INSTALL_DIR/requirements.txt

# Create the configuration file
cat << EOF >  $CONFIGURATION_DIR/.env
OPENAI_API_KEY=<YOUR_API_KEY_HERE>
EOF

# Create the gptd.service file
cat << EOF > $SERVICE_FILE
[Unit]
Description=gptd

[Service]
ExecStart=/usr/local/lib/gpt.d/gptd.py
User=$SUDO_USER
Group=$(id -gn $SUDO_USER)
EnvironmentFile=/etc/gpt.d/.env
Restart=no

[Install]
WantedBy=multi-user.target
EOF

# Reload the systemd daemon to recognize the new service
systemctl daemon-reload

# Enable the service so it starts on boot
systemctl start gptd
